# 01 – Explore and data quality
Data: public pump sensor dataset (Kaggle), 1-minute readings, Apr–Aug 2018

In [127]:
import pandas as pd
import numpy as np

In [128]:
data= pd.read_csv("../data/raw/sensor.csv")

In [129]:
data.head()

,Unnamed: 0,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [130]:
data.describe().T

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,220320.0,110159.500000,63601.049991,0.000000,55079.750000,110159.500000,165239.250000,220319.000000
sensor_00,210112.0,2.372221,0.412227,0.000000,2.438831,2.456539,2.499826,2.549016
sensor_01,219951.0,47.591611,3.296666,0.000000,46.310760,48.133678,49.479160,56.727430
sensor_02,220301.0,50.867392,3.666820,33.159720,50.390620,51.649300,52.777770,56.032990
sensor_03,220301.0,43.752481,2.418887,31.640620,42.838539,44.227428,45.312500,48.220490
sensor_04,220301.0,590.673936,144.023912,2.798032,626.620400,632.638916,637.615723,800.000000
sensor_05,220301.0,73.396414,17.298247,0.000000,69.976260,75.576790,80.912150,99.999880
sensor_06,215522.0,13.501537,2.163736,0.014468,13.346350,13.642940,14.539930,22.251160
sensor_07,214869.0,15.843152,2.201155,0.000000,15.907120,16.167530,16.427950,23.596640
sensor_08,215213.0,15.200721,2.037390,0.028935,15.183740,15.494790,15.697340,24.348960
sensor_09,215725.0,14.799210,2.091963,0.000000,15.053530,15.082470,15.118630,25.000000
sensor_10,220301.0,41.470339,12.093519,0.000000,40.705260,44.291340,47.463760,76.106860
sensor_11,220301.0,41.918319,13.056425,0.000000,38.856420,45.363140,49.656540,60.000000
sensor_12,220301.0,29.136975,10.113935,0.000000,28.686810,32.515830,34.939730,45.000000
sensor_13,220301.0,7.078858,6.901755,0.000000,1.538516,2.929809,12.859520,31.187550
sensor_14,220299.0,376.860041,113.206382,32.409550,418.103250,420.106200,420.997100,500.000000
sensor_15,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sensor_16,220289.0,416.472892,126.072642,0.000000,459.453400,462.856100,464.302700,739.741500
sensor_17,220274.0,421.127517,129.156175,0.000000,454.138825,462.020250,466.857075,599.999939
sensor_18,220274.0,2.303785,0.765883,0.000000,2.447542,2.533704,2.587682,4.873250
sensor_19,220304.0,590.829775,199.345820,0.000000,662.768975,665.672400,667.146700,878.917900
sensor_20,220304.0,360.805165,101.974118,0.000000,398.021500,399.367000,400.088400,448.907900
sensor_21,220304.0,796.225942,226.679317,95.527660,875.464400,879.697600,882.129900,1107.526000
sensor_22,220279.0,459.792815,154.528337,0.000000,478.962600,531.855900,534.254850,594.061100
sensor_23,220304.0,922.609264,291.835280,0.000000,950.922400,981.925000,1090.808000,1227.564000
sensor_24,220304.0,556.235397,182.297979,0.000000,601.151050,625.873500,628.607725,1000.000000
sensor_25,220284.0,649.144799,220.865166,0.000000,693.957800,740.203500,750.357125,839.575000
sensor_26,220300.0,786.411781,246.663608,43.154790,790.489575,861.869600,919.104775,1214.420000
sensor_27,220304.0,501.506589,169.823173,0.000000,448.297950,494.468450,536.274550,2000.000000
sensor_28,220304.0,851.690339,313.074032,4.319347,782.682625,967.279850,1043.976500,1841.146000
sensor_29,220248.0,576.195305,225.764091,0.636574,518.947225,564.872500,744.021475,1466.281000
sensor_30,220059.0,614.596442,195.726872,0.000000,627.777800,668.981400,697.222200,1600.000000
sensor_31,220304.0,863.323100,283.544760,23.958330,839.062400,917.708300,981.249900,1800.000000
sensor_32,220252.0,804.283915,260.602361,0.240716,760.607475,878.850750,943.877625,1839.211000
sensor_33,220304.0,486.405980,150.751836,6.460602,489.761075,512.271750,555.163225,1578.600000
sensor_34,220304.0,234.971776,88.376065,54.882370,172.486300,226.356050,316.844950,425.549800
sensor_35,220304.0,427.129817,141.772519,0.000000,353.176625,473.349350,528.891025,694.479126
sensor_36,220304.0,593.033876,289.385511,2.260970,288.547575,709.668050,837.333025,984.060700
sensor_37,220304.0,60.787360,37.604883,0.000000,28.799220,64.295485,90.821927,174.901200
sensor_38,220293.0,49.655946,10.540397,24.479166,45.572910,49.479160,53.645830,417.708300
sensor_39,220293.0,36.610444,15.613723,19.270830,32.552080,35.416660,39.062500,547.916600
sensor_40,220293.0,68.844530,21.371139,23.437500,57.812500,66.406250,77.864580,512.760400
sensor_41,220293.0,35.365126,7.898665,20.833330,32.552080,34.895832,37.760410,420.312500
sensor_42,220293.0,35.453455,10.259521,22.135416,32.812500,35.156250,36.979164,374.218800
sensor_43,220293.0,43.879591,11.044404,24.479166,39.583330,42.968750,46.614580,408.593700
sensor_44,220293.0,42.656877,11.576355,25.752316,36.747684,40.509260,45.138890,1000.000000
sensor_45,220293.0,43.094984,12.837520,26.331018,36.747684,40.219910,44.849540,320.312500
sensor_46,220293.0,48.018585,15.641284,26.331018,40.509258,44.849540,51.215280,370.370400
sensor_47,220293.0,44.340903,10.442437,27.199070,39.062500,42.534720,46.585650,303.530100
sensor_48,220293.0,150.889044,82.244957,26.331018,83.912030,138.020800,208.333300,561.632000
sensor_49,220293.0,57.119968,19.143598,26.620370,47.743060,52.662040,60.763890,464.409700
sensor_50,143303.0,183.049260,65.258650,27.488426,167.534700,193.865700,219.907400,1000.000000
sensor_51,204937.0,202.699667,109.588607,27.777779,179.108800,197.338000,216.724500,1000.000000

In [131]:
data=data.drop(columns="Unnamed: 0")

In [132]:
data.head()

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [133]:
data.duplicated().sum()

np.int64(0)

No duplicate rows!

In [134]:
data["timestamp"].dtype

In [135]:
data["timestamp"]=pd.to_datetime(data["timestamp"], errors='coerce')

In [136]:
data.head()

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [137]:
data["timestamp"].dtype

dtype('<M8[us]')

In [138]:
data["timestamp"].min(), data["timestamp"].max()

(Timestamp('2018-04-01 00:00:00'), Timestamp('2018-08-31 23:59:00'))

Our data is from April 1st 2018 to August 8, 2018 (11:59 PM)

In [183]:
data["machine_status"].unique()

<ArrowStringArray>
['NORMAL', 'BROKEN', 'RECOVERING']
Length: 3, dtype: str

In [186]:
broken=data[data["machine_status"]=="BROKEN"]

broken

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
17155,2018-04-12 21:55:00,0.000000,53.342010,52.821180,43.402775,202.526031,49.79289,3.219039,16.890910,16.869210,...,50.78125,50.92593,51.215280,50.636570,46.006940,409.143500,121.527800,401.909700,324.6528,BROKEN
24510,2018-04-18 00:30:00,1.093982,42.534720,47.699650,41.449650,206.038757,60.30106,12.304690,15.154800,14.185470,...,42.70833,34.72222,31.539350,34.432870,33.275460,59.895830,44.560180,177.662000,183.7384,BROKEN
69318,2018-05-19 03:18:00,2.258796,47.265630,52.734370,43.446178,200.115738,66.14643,13.592300,15.914350,15.147570,...,39.06250,35.01157,37.905090,39.062500,45.428240,144.675900,49.768520,246.238400,257.5231,BROKEN
77790,2018-05-25 00:30:00,2.321759,47.482640,51.475693,42.795135,612.152800,67.30158,14.062500,16.608800,15.943290,...,202.34370,65.68287,57.870370,127.893500,153.935200,155.381900,65.682870,220.196800,267.3611,BROKEN
128040,2018-06-28 22:00:00,0.364005,40.190970,45.225690,40.190971,201.368622,0.00000,11.335360,15.270540,15.183740,...,32.29166,28.06713,28.067129,29.513889,29.224537,29.224537,29.513889,32.407406,NaN,BROKEN
141131,2018-07-08 00:11:00,0.001968,45.138890,52.907990,45.355900,500.000000,1.40131,0.028935,0.036169,0.036169,...,36.19791,37.32639,35.300930,38.194440,43.402780,99.537030,44.849540,192.129600,174.7685,BROKEN
166440,2018-07-25 14:00:00,2.318808,45.833332,52.994790,43.880210,420.503448,72.52040,14.185470,16.247110,15.697340,...,51.30208,52.10200,52.662040,67.129630,43.981480,230.324100,69.733800,NaN,205.7292,BROKEN

In the time period for when the data is tracked the pump was "broken" a total of 7 times.

In [194]:
recovering=data[data["machine_status"]=="RECOVERING"]


print(recovering.shape)
recovering

(14477, 53)

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
17156,2018-04-12 21:56:00,0.000000,53.55902,52.777770,43.402775,204.725098,53.74214,3.045428,17.42621,15.740740,...,49.479160,50.34722,51.21528,49.18982,49.47917,431.7130,133.1019,419.2708,341.7245,RECOVERING
17157,2018-04-12 21:57:00,0.000000,53.55902,52.777770,43.402775,201.137131,52.49996,7.537616,13.53443,9.324364,...,48.177080,49.76852,50.92593,48.03241,53.81944,451.3889,140.0463,433.1597,466.1458,RECOVERING
17158,2018-04-12 21:58:00,0.000000,52.77777,52.690970,43.402770,204.030655,57.19875,7.609953,16.60880,16.203700,...,46.875000,48.03241,50.34722,47.45370,58.15972,466.4352,144.9653,442.7083,366.0301,RECOVERING
17159,2018-04-12 21:59:00,0.000000,52.60416,52.734370,43.446180,203.567688,50.96181,7.573785,16.70284,16.160300,...,45.833330,47.45370,49.76852,46.58565,63.65741,474.8264,149.0162,449.6528,374.4213,RECOVERING
17160,2018-04-12 22:00:00,NaN,52.51736,52.690970,43.446180,203.567688,49.78948,7.559317,16.56539,16.239870,...,44.270830,46.29630,48.03241,45.13889,75.23148,477.7199,162.6157,448.7847,356.1921,RECOVERING
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
166511,2018-07-25 15:11:00,0.310880,46.48438,51.171870,46.527775,152.526031,60.77931,15.089700,17.62876,18.200230,...,59.895830,77.83565,73.78472,58.44907,58.15972,295.4283,260.4167,NaN,211.2269,RECOVERING
166512,2018-07-25 15:12:00,0.304977,46.39757,51.085070,46.527770,152.178802,61.24545,15.089700,17.62153,18.243630,...,58.854160,75.81019,69.44444,56.71296,58.15972,278.9352,244.2130,NaN,195.0231,RECOVERING
166513,2018-07-25 15:13:00,0.303993,46.31076,51.085070,46.484380,151.021393,52.94817,15.125870,17.62153,18.236400,...,57.552080,81.30787,65.10416,53.81944,60.47454,267.9398,229.1667,NaN,180.5556,RECOVERING
166514,2018-07-25 15:14:00,0.301042,46.18055,51.041664,46.484380,152.988983,53.20142,15.089700,17.66493,18.301500,...,57.552082,96.64352,62.21065,52.37268,63.94676,262.4421,216.7245,NaN,168.1134,RECOVERING
166515,2018-07-25 15:15:00,0.301042,46.09375,50.998260,46.440970,151.252900,56.64543,15.118630,17.67940,18.127890,...,57.552080,111.40050,59.31713,51.21528,65.68287,258.6805,211.2269,NaN,157.4074,RECOVERING

There are 14,477 minutes where the pump is classsified as "recovering".

### NULL values

In [139]:
missing_pct= data.isnull().mean() * 100
missing_pct.sort_values(ascending=False).round(1)

sensor_15         100.0
sensor_50          35.0
sensor_51           7.0
sensor_00           4.6
sensor_07           2.5
sensor_08           2.3
sensor_06           2.2
sensor_09           2.1
sensor_01           0.2
sensor_30           0.1
sensor_29           0.0
sensor_32           0.0
sensor_18           0.0
sensor_17           0.0
sensor_22           0.0
sensor_25           0.0
sensor_16           0.0
sensor_49           0.0
sensor_48           0.0
sensor_47           0.0
sensor_46           0.0
sensor_45           0.0
sensor_44           0.0
sensor_43           0.0
sensor_42           0.0
sensor_41           0.0
sensor_40           0.0
sensor_39           0.0
sensor_38           0.0
sensor_14           0.0
sensor_26           0.0
sensor_03           0.0
sensor_10           0.0
sensor_13           0.0
sensor_12           0.0
sensor_11           0.0
sensor_05           0.0
sensor_04           0.0
sensor_02           0.0
sensor_36           0.0
sensor_37           0.0
sensor_28           0.0
sensor_27           0.0
sensor_31           0.0
sensor_35           0.0
sensor_24           0.0
sensor_23           0.0
sensor_34           0.0
sensor_21           0.0
sensor_20           0.0
sensor_19           0.0
sensor_33           0.0
timestamp           0.0
machine_status      0.0
dtype: float64

In [158]:
over_1=missing_pct[missing_pct>1].sort_values(ascending=False)
over_1

sensor_15    100.000000
sensor_50     34.956881
sensor_51      6.982117
sensor_00      4.633261
sensor_07      2.474129
sensor_08      2.317992
sensor_06      2.177741
sensor_09      2.085603
dtype: float64

In [140]:
type(missing_pct)

pandas.Series

In [141]:
sensor_cols = [c for c in data.columns if c.startswith("sensor")]
len(sensor_cols)

52

In [142]:
missing_per_row = data[sensor_cols].isna().sum(axis=1)
missing_per_row

0         1
1         1
2         1
3         1
4         1
         ..
220315    2
220316    2
220317    2
220318    2
220319    2
Length: 220320, dtype: int64

For each minute we can see how many sensors had a null or no recording. Sensor 15 had every value missing so every minute has AT LEAST 1 missing sensor.

In [143]:
missing_per_row.value_counts().sort_index()

1     119103
2      93865
3       2459
4         96
5        290
6       3841
7        634
15         8
24         3
25         2
29         8
52        11
Name: count, dtype: int64

We can see that the most of the the time only 1 (sesnor 15) or 2 sensors are missing per minute/row. There are a few instances where there are three or 6 sensors also missing. Theres 11 instances were all 52 sensors are missing so those will definetly need to be dropped as theres no value in those rows!

Also In 11 minutes, all 52 sensors were missing at the same timestamp, and in another 21 minutes, 15 to 29 sensors were missing at the same timestamp. Many sensors being blank in the same minute suggests a data collection issue rather than individual sensor faults. Whether these were one outage or several is checked below.

In [144]:
data.loc[missing_per_row > 40, ["timestamp", "machine_status"]]

                 timestamp machine_status
38508  2018-04-27 17:48:00         NORMAL
38509  2018-04-27 17:49:00         NORMAL
38510  2018-04-27 17:50:00         NORMAL
38511  2018-04-27 17:51:00         NORMAL
38512  2018-04-27 17:52:00         NORMAL
38513  2018-04-27 17:53:00         NORMAL
38514  2018-04-27 17:54:00         NORMAL
38515  2018-04-27 17:55:00         NORMAL
145992 2018-07-11 09:12:00         NORMAL
145993 2018-07-11 09:13:00         NORMAL
145994 2018-07-11 09:14:00         NORMAL

In [145]:
data.loc[missing_per_row.between(15, 29), ["timestamp", "machine_status"]]

                 timestamp machine_status
25112  2018-04-18 10:32:00     RECOVERING
48522  2018-05-04 16:42:00         NORMAL
48564  2018-05-04 17:24:00         NORMAL
87832  2018-05-31 23:52:00         NORMAL
87833  2018-05-31 23:53:00         NORMAL
87834  2018-05-31 23:54:00         NORMAL
87835  2018-05-31 23:55:00         NORMAL
87836  2018-05-31 23:56:00         NORMAL
87837  2018-05-31 23:57:00         NORMAL
87838  2018-05-31 23:58:00         NORMAL
87839  2018-05-31 23:59:00         NORMAL
113141 2018-06-18 13:41:00         NORMAL
134855 2018-07-03 15:35:00     RECOVERING
134873 2018-07-03 15:53:00     RECOVERING
136197 2018-07-04 13:57:00     RECOVERING
136265 2018-07-04 15:05:00     RECOVERING
146035 2018-07-11 09:55:00         NORMAL
147679 2018-07-12 13:19:00         NORMAL
220008 2018-08-31 18:48:00         NORMAL
220009 2018-08-31 18:49:00         NORMAL
220010 2018-08-31 18:50:00         NORMAL

- Full blackouts (all 52 sensors): April 27 17:48 to 17:55 and July 11 09:12 to 09:14, both while the pump was running normally. This points to a data collection problem.
- Partial dropouts (15 to 29 sensors): two multi-minute periods (May 31 23:52 to 23:59; Aug 31 18:48 to 18:50), a few minutes during RECOVERING (Apr 18, Jul 3 to 4), and scattered single minutes.

**It would be benefical to check with the operations team and PI team to understand/clairify what was happening at the pump at these times!**

### TimeStamp Check

In [146]:
data.head()

,timestamp,sensor_00,sensor_01,sensor_02,sensor_03,sensor_04,sensor_05,sensor_06,sensor_07,sensor_08,...,sensor_43,sensor_44,sensor_45,sensor_46,sensor_47,sensor_48,sensor_49,sensor_50,sensor_51,machine_status
0,2018-04-01 00:00:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
1,2018-04-01 00:01:00,2.465394,47.09201,53.2118,46.310760,634.3750,76.45975,13.41146,16.13136,15.56713,...,41.92708,39.641200,65.68287,50.92593,38.194440,157.9861,67.70834,243.0556,201.3889,NORMAL
2,2018-04-01 00:02:00,2.444734,47.35243,53.2118,46.397570,638.8889,73.54598,13.32465,16.03733,15.61777,...,41.66666,39.351852,65.39352,51.21528,38.194443,155.9606,67.12963,241.3194,203.7037,NORMAL
3,2018-04-01 00:03:00,2.460474,47.09201,53.1684,46.397568,628.1250,76.98898,13.31742,16.24711,15.69734,...,40.88541,39.062500,64.81481,51.21528,38.194440,155.9606,66.84028,240.4514,203.1250,NORMAL
4,2018-04-01 00:04:00,2.445718,47.13541,53.2118,46.397568,636.4583,76.58897,13.35359,16.21094,15.69734,...,41.40625,38.773150,65.10416,51.79398,38.773150,158.2755,66.55093,242.1875,201.3889,NORMAL

In [147]:
data["timestamp"].diff().value_counts()

timestamp
0 days 00:01:00    220319
Name: count, dtype: int64

This shows that every minute is being tracked so no mintues have been excluded or missing from the timeline.

### Which columns to keep?

In [148]:
data[["sensor_15"]].isnull().sum()

sensor_15    220320
dtype: int64

We can definelty drop this column!

In [150]:
data=data.drop(columns="sensor_15")

In [151]:
data.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['timestamp', 'sensor_00', 'sensor_01', 'sensor_02', 'sensor_03',
       'sensor_04', 'sensor_05', 'sensor_06', 'sensor_07', 'sensor_08',
       'sensor_09', 'sensor_10', 'sensor_11', 'sensor_12', 'sensor_13',
       'sensor_14', 'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19',
       'sensor_20', 'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24',
       'sensor_25', 'sensor_26', 'sensor_27', 'sensor_28', 'sensor_29',
       'sensor_30', 'sensor_31', 'sensor_32', 'sensor_33', 'sensor_34',
       'sensor_35', 'sensor_36', 'sensor_37', 'sensor_38', 'sensor_39',
       'sensor_40', 'sensor_41', 'sensor_42', 'sensor_43', 'sensor_44',
       'sensor_45', 'sensor_46', 'sensor_47', 'sensor_48', 'sensor_49',
       'sensor_50', 'sensor_51', 'machine_status'],
      dtype='str')>

In [153]:
sensor_cols = [c for c in data.columns if c.startswith("sensor")]
len(sensor_cols)

51

In [159]:
over_1

sensor_15    100.000000
sensor_50     34.956881
sensor_51      6.982117
sensor_00      4.633261
sensor_07      2.474129
sensor_08      2.317992
sensor_06      2.177741
sensor_09      2.085603
dtype: float64

### Decisions

| Sensor | Missing | Decision | Why |
|---|---|---|---|
| sensor_15 | 100% | Drop | Completely empty, no data to use |
| sensor_50 | 35.0% | Flag | A third missing; use with care, not as a main signal |
| sensor_51 | 7.0% | Flag | Noticeable gaps |
| sensor_00 | 4.6% | Flag | Noticeable gaps |
| sensor_07 | 2.5% | Flag | Over 1% missing |
| sensor_08 | 2.3% | Flag | Over 1% missing |
| sensor_06 | 2.2% | Flag | Over 1% missing |
| sensor_09 | 2.1% | Flag | Over 1% missing |

All other sensors (under 1% missing): **keep**.

**Collection outages:** all sensors were blank on April 27 (17:48 to 17:55) and July 11 (09:12 to 09:14), plus partial dropouts on a few other dates. These aren't a per-sensor problem since everyhting was empty.

### The Tag Table

In [162]:
labels=pd.read_csv("../reference/ibm_sensor_labels.csv")

In [163]:
labels

   sensor_column                                description tag_code
0      sensor_00                     Motor Casing Vibration      VIB
1      sensor_01                          Motor Frequency A     FREQ
2      sensor_02                          Motor Frequency B     FREQ
3      sensor_03                          Motor Frequency C     FREQ
4      sensor_04                                Motor Speed      SPD
5      sensor_05                              Motor Current     CURR
6      sensor_06                         Motor Active Power      PWR
7      sensor_07                       Motor Apparent Power      PWR
8      sensor_08                       Motor Reactive Power      PWR
9      sensor_09                          Motor Shaft Power      PWR
10     sensor_10                      Motor Phase Current A     CURR
11     sensor_11                      Motor Phase Current B     CURR
12     sensor_12                      Motor Phase Current C     CURR
13     sensor_13                   Motor Coupling Vibration      VIB
14     sensor_14                     Motor Phase Voltage AB     VOLT
15     sensor_16                     Motor Phase Voltage BC     VOLT
16     sensor_17                     Motor Phase Voltage CA     VOLT
17     sensor_18                      Pump Casing Vibration      VIB
18     sensor_19                Pump Stage 1 Impeller Speed      SPD
19     sensor_20                Pump Stage 1 Impeller Speed      SPD
20     sensor_21                Pump Stage 1 Impeller Speed      SPD
21     sensor_22                Pump Stage 1 Impeller Speed      SPD
22     sensor_23                Pump Stage 1 Impeller Speed      SPD
23     sensor_24                Pump Stage 1 Impeller Speed      SPD
24     sensor_25                Pump Stage 2 Impeller Speed      SPD
25     sensor_26                Pump Stage 2 Impeller Speed      SPD
26     sensor_27                Pump Stage 2 Impeller Speed      SPD
27     sensor_28                Pump Stage 2 Impeller Speed      SPD
28     sensor_29                Pump Stage 2 Impeller Speed      SPD
29     sensor_30                Pump Stage 2 Impeller Speed      SPD
30     sensor_31                Pump Stage 2 Impeller Speed      SPD
31     sensor_32                Pump Stage 2 Impeller Speed      SPD
32     sensor_33                Pump Stage 2 Impeller Speed      SPD
33     sensor_34                            Pump Inlet Flow     FLOW
34     sensor_35                        Pump Discharge Flow     FLOW
35     sensor_36                               Pump Unknown      UNK
36     sensor_37     Pump Lube Oil Overhead Reservoir Level      LVL
37     sensor_38                  Pump Lube Oil Return Temp     TEMP
38     sensor_39                  Pump Lube Oil Supply Temp     TEMP
39     sensor_40            Pump Thrust Bearing Active Temp     TEMP
40     sensor_41  Motor Non Drive End Radial Bearing Temp 1     TEMP
41     sensor_42  Motor Non Drive End Radial Bearing Temp 2     TEMP
42     sensor_43          Pump Thrust Bearing Inactive Temp     TEMP
43     sensor_44       Pump Drive End Radial Bearing Temp 1     TEMP
44     sensor_45   Pump Non Drive End Radial Bearing Temp 1     TEMP
45     sensor_46   Pump Non Drive End Radial Bearing Temp 2     TEMP
46     sensor_47       Pump Drive End Radial Bearing Temp 2     TEMP
47     sensor_48                        Pump Inlet Pressure    PRESS
48     sensor_49                          Pump Temp Unknown     TEMP
49     sensor_50                  Pump Discharge Pressure 1    PRESS
50     sensor_51                  Pump Discharge Pressure 2    PRESS

### About the sensor labels

The Kaggle dataset hides what each sensor measures. The columns are only named `sensor_00` to `sensor_51`, with no descriptions or units.

**Where the descriptions come from:** IBM used this same public pump dataset in a free training lab for its Maximo maintenance software. That lab lists what IBM believes each sensor measures (for example, `sensor_04` = Motor Speed, `sensor_50` = Pump Discharge Pressure 1).
Source: [IBM Maximo APM lab: Pump Data Dictionary](https://ibm.github.io/maximo-labs-archive/apm_8.7/data_dictionary)

These are IBM's best guesses, not official information from whoever collected the data, so treat them with some caution.

**The reference file:** `reference/ibm_sensor_labels.csv` was put together with help from Claude (an AI assistant). It contains:
- `sensor_column`: the original column name in the data
- `description`: IBM's description of the sensor
- `tag_code`: a short code for the type of measurement (for example VIB = vibration, SPD = speed, PRESS = pressure, TEMP = temperature), added to build readable tag names

sensor_15 is not included, because it was dropped (100% missing) and IBM's list has no entry for it either.

**Tag names:** in an industrial data historian like the AVEVA PI System, every sensor has a tag name that follows a naming convention, usually combining the site, the equipment and the type of measurement. To mimic that, each sensor here gets a PI-style name in the format `PUMP01.<TYPE>.<NUMBER>`, for example `PUMP01.SPD.04`.  The tags use **periods (`.`) instead of underscores**.The tag names reflect the hierarchy, pump, then measurement type, then sensor number, which is a common naming convention. In a real PI system, the full hierarchy would live in Asset Framework.

In [164]:
tags = labels.copy()
tags.head()

  sensor_column             description tag_code
0     sensor_00  Motor Casing Vibration      VIB
1     sensor_01       Motor Frequency A     FREQ
2     sensor_02       Motor Frequency B     FREQ
3     sensor_03       Motor Frequency C     FREQ
4     sensor_04             Motor Speed      SPD

In [168]:
tags["tag_name"] = "PUMP01." + tags["tag_code"] + "." + tags["sensor_column"].str[-2:]
tags.head()

  sensor_column             description tag_code        tag_name
0     sensor_00  Motor Casing Vibration      VIB   PUMP01.VIB.00
1     sensor_01       Motor Frequency A     FREQ  PUMP01.FREQ.01
2     sensor_02       Motor Frequency B     FREQ  PUMP01.FREQ.02
3     sensor_03       Motor Frequency C     FREQ  PUMP01.FREQ.03
4     sensor_04             Motor Speed      SPD   PUMP01.SPD.04

In [175]:
tags["units"] = "unknown"
tags["missing_pct"] = tags["sensor_column"].map(missing_pct).round(2)
tags.head()

,sensor_column,description,tag_code,tag_name,units,missing_pct
0,sensor_00,Motor Casing Vibration,VIB,PUMP01.VIB.00,unknown,4.63
1,sensor_01,Motor Frequency A,FREQ,PUMP01.FREQ.01,unknown,0.17
2,sensor_02,Motor Frequency B,FREQ,PUMP01.FREQ.02,unknown,0.01
3,sensor_03,Motor Frequency C,FREQ,PUMP01.FREQ.03,unknown,0.01
4,sensor_04,Motor Speed,SPD,PUMP01.SPD.04,unknown,0.01

In [177]:
def quality_note(pct):
    if pct > 1:
        return f"Flagged: {pct}% missing"
    return "OK"

tags["quality_note"] = tags["missing_pct"].apply(quality_note)

In [181]:
tags = tags[["tag_name", "sensor_column", "description", "units", "missing_pct", "quality_note"]]
print(tags.shape)
tags

(51, 6)

,tag_name,sensor_column,description,units,missing_pct,quality_note
0,PUMP01.VIB.00,sensor_00,Motor Casing Vibration,unknown,4.63,Flagged: 4.63% missing
1,PUMP01.FREQ.01,sensor_01,Motor Frequency A,unknown,0.17,OK
2,PUMP01.FREQ.02,sensor_02,Motor Frequency B,unknown,0.01,OK
3,PUMP01.FREQ.03,sensor_03,Motor Frequency C,unknown,0.01,OK
4,PUMP01.SPD.04,sensor_04,Motor Speed,unknown,0.01,OK
5,PUMP01.CURR.05,sensor_05,Motor Current,unknown,0.01,OK
6,PUMP01.PWR.06,sensor_06,Motor Active Power,unknown,2.18,Flagged: 2.18% missing
7,PUMP01.PWR.07,sensor_07,Motor Apparent Power,unknown,2.47,Flagged: 2.47% missing
8,PUMP01.PWR.08,sensor_08,Motor Reactive Power,unknown,2.32,Flagged: 2.32% missing
9,PUMP01.PWR.09,sensor_09,Motor Shaft Power,unknown,2.09,Flagged: 2.09% missing
10,PUMP01.CURR.10,sensor_10,Motor Phase Current A,unknown,0.01,OK
11,PUMP01.CURR.11,sensor_11,Motor Phase Current B,unknown,0.01,OK
12,PUMP01.CURR.12,sensor_12,Motor Phase Current C,unknown,0.01,OK
13,PUMP01.VIB.13,sensor_13,Motor Coupling Vibration,unknown,0.01,OK
14,PUMP01.VOLT.14,sensor_14,Motor Phase Voltage AB,unknown,0.01,OK
15,PUMP01.VOLT.16,sensor_16,Motor Phase Voltage BC,unknown,0.01,OK
16,PUMP01.VOLT.17,sensor_17,Motor Phase Voltage CA,unknown,0.02,OK
17,PUMP01.VIB.18,sensor_18,Pump Casing Vibration,unknown,0.02,OK
18,PUMP01.SPD.19,sensor_19,Pump Stage 1 Impeller Speed,unknown,0.01,OK
19,PUMP01.SPD.20,sensor_20,Pump Stage 1 Impeller Speed,unknown,0.01,OK
20,PUMP01.SPD.21,sensor_21,Pump Stage 1 Impeller Speed,unknown,0.01,OK
21,PUMP01.SPD.22,sensor_22,Pump Stage 1 Impeller Speed,unknown,0.02,OK
22,PUMP01.SPD.23,sensor_23,Pump Stage 1 Impeller Speed,unknown,0.01,OK
23,PUMP01.SPD.24,sensor_24,Pump Stage 1 Impeller Speed,unknown,0.01,OK
24,PUMP01.SPD.25,sensor_25,Pump Stage 2 Impeller Speed,unknown,0.02,OK
25,PUMP01.SPD.26,sensor_26,Pump Stage 2 Impeller Speed,unknown,0.01,OK
26,PUMP01.SPD.27,sensor_27,Pump Stage 2 Impeller Speed,unknown,0.01,OK
27,PUMP01.SPD.28,sensor_28,Pump Stage 2 Impeller Speed,unknown,0.01,OK
28,PUMP01.SPD.29,sensor_29,Pump Stage 2 Impeller Speed,unknown,0.03,OK
29,PUMP01.SPD.30,sensor_30,Pump Stage 2 Impeller Speed,unknown,0.12,OK
30,PUMP01.SPD.31,sensor_31,Pump Stage 2 Impeller Speed,unknown,0.01,OK
31,PUMP01.SPD.32,sensor_32,Pump Stage 2 Impeller Speed,unknown,0.03,OK
32,PUMP01.SPD.33,sensor_33,Pump Stage 2 Impeller Speed,unknown,0.01,OK
33,PUMP01.FLOW.34,sensor_34,Pump Inlet Flow,unknown,0.01,OK
34,PUMP01.FLOW.35,sensor_35,Pump Discharge Flow,unknown,0.01,OK
35,PUMP01.UNK.36,sensor_36,Pump Unknown,unknown,0.01,OK
36,PUMP01.LVL.37,sensor_37,Pump Lube Oil Overhead Reservoir Level,unknown,0.01,OK
37,PUMP01.TEMP.38,sensor_38,Pump Lube Oil Return Temp,unknown,0.01,OK
38,PUMP01.TEMP.39,sensor_39,Pump Lube Oil Supply Temp,unknown,0.01,OK
39,PUMP01.TEMP.40,sensor_40,Pump Thrust Bearing Active Temp,unknown,0.01,OK
40,PUMP01.TEMP.41,sensor_41,Motor Non Drive End Radial Bearing Temp 1,unknown,0.01,OK
41,PUMP01.TEMP.42,sensor_42,Motor Non Drive End Radial Bearing Temp 2,unknown,0.01,OK
42,PUMP01.TEMP.43,sensor_43,Pump Thrust Bearing Inactive Temp,unknown,0.01,OK
43,PUMP01.TEMP.44,sensor_44,Pump Drive End Radial Bearing Temp 1,unknown,0.01,OK
44,PUMP01.TEMP.45,sensor_45,Pump Non Drive End Radial Bearing Temp 1,unknown,0.01,OK
45,PUMP01.TEMP.46,sensor_46,Pump Non Drive End Radial Bearing Temp 2,unknown,0.01,OK
46,PUMP01.TEMP.47,sensor_47,Pump Drive End Radial Bearing Temp 2,unknown,0.01,OK
47,PUMP01.PRESS.48,sensor_48,Pump Inlet Pressure,unknown,0.01,OK
48,PUMP01.TEMP.49,sensor_49,Pump Temp Unknown,unknown,0.01,OK
49,PUMP01.PRESS.50,sensor_50,Pump Discharge Pressure 1,unknown,34.96,Flagged: 34.96% missing
50,PUMP01.PRESS.51,sensor_51,Pump Discharge Pressure 2,unknown,6.98,Flagged: 6.98% missing